name: cnn_drone_net
channels:
  - pytorch
  - defaults
  - conda-forge
  - powerai
  - pypi
dependencies:
  - python=3.7.4
  - pytorch=1.3.0
  - torchvision=0.4.1
  - pillow<7.0 # version 7 breaks torchvision 0.4.2 and earlier
  - ipython>=7.9
  - numpy
  - scikit-learn
  - cudatoolkit
  - jupyterlab
  - matplotlib
  - jupyter
  - pandas
  - cython
  - pytest
  - tqdm
  - opencv
  - ffmpeg>4.1
  - freetype>=2.10
  - swig # for box2d on Windows
  - urllib3
  - seaborn
  - mistune
  - pip
  - pip:
      - nbmerge
      - pytest-xdist
      - gym
      - atari-py
      - box2d-py
      - torch
      - scikit-learn
